# This file is not used, it's a template for how the environment specific secrets files that are not committed should look.

# Encrypt secrets by doing:
# java -cp ./jasypt-1.9.3.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI password=<password> input=<input> algorithm=PBEWITHHMACSHA512ANDAES_256 ivGeneratorClassName=org.jasypt.iv.RandomIvGenerator
# Provide decryption password as -e JASYPT_ENCRYPTOR_PASSWORD=<password> when starting Docker container.

app:
  security:
    keystore:
      # Create keystore with: keytool -genkey -alias <alias> -keyalg RSA -keystore <profile>-keystore.jks -keysize 2048 -validity 9999
      location:
      password:
      keyAlias:
      privateKeyPassphrase:
    allowedOrigins:

spring:
  datasource:
    username:
    password:
    url:
  mail:
    username:
    password:
